name: Terraform Workflow

on:
  push:
    branches:
      - branch2
  pull_request:
    branches:
      - branch2

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: terraform_plan
        run: terraform plan -out=terraform.tfplan

      - name: Create a new branch and commit Terraform Plan
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -b terraform-plan-branch
          git add terraform.tfplan
          git commit -m "Add Terraform plan"
          git push origin terraform-plan-branch

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth login --with-token <<< $GITHUB_TOKEN
          gh pr create --title "Terraform Plan Output" --body "This PR includes the Terraform plan output. Please review the changes." --head terraform-plan-branch --base main

  merge:
    runs-on: ubuntu-latest
    needs: terraform
    if: github.event_name == 'pull_request' && github.event.action == 'review_requested'
    steps:
      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Merge Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth login --with-token <<< $GITHUB_TOKEN
          gh pr merge ${{ github.event.pull_request.number }} --merge --body "Merging Terraform Plan PR"
