name: Terraform Workflow

on:
  push:
    branches:
      - branch2

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: terraform_plan
        run: terraform plan -out=terraform.tfplan

      - name: Create Pull Request
        if: success()  # Create PR only if Terraform Plan succeeded
        uses: octokit/request-action@v2
        with:
          route: POST /repos/${{ github.repository }}/pulls
          title: "Terraform Plan Output"
          body: "This PR includes the Terraform plan output. Please review the changes."
          head: terraform-plan-branch
          base: branch2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  validate:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Check for code validation
        run: |
          echo "Add your code validation steps here. For example, linting, static analysis, etc."
